"""Tambahkan index untuk optimasi query (fix)

Revision ID: 989db14b81c1
Revises: 
Create Date: 2025-10-06 14:35:15.945350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989db14b81c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_homeroom_teacher_id'), ['homeroom_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_school_id'), ['school_id'], unique=False)

    with op.batch_alter_table('school_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_events_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_events_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_events_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('school_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_subscriptions_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_subscriptions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_subscriptions_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schools_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_schools_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_schools_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_nis'), ['nis'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_nisn'), ['nisn'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('teacher_attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_attendances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_attendances_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_attendances_teacher_id'), ['teacher_id'], unique=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_nip'), ['nip'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_school_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_nip'))

    with op.batch_alter_table('teacher_attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_attendances_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_attendances_school_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_attendances_date'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_school_id'))
        batch_op.drop_index(batch_op.f('ix_students_nisn'))
        batch_op.drop_index(batch_op.f('ix_students_nis'))
        batch_op.drop_index(batch_op.f('ix_students_classroom_id'))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_is_active'))
        batch_op.drop_index(batch_op.f('ix_schools_code'))
        batch_op.create_unique_constraint(batch_op.f('schools_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('school_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_subscriptions_start_date'))
        batch_op.drop_index(batch_op.f('ix_school_subscriptions_is_active'))
        batch_op.drop_index(batch_op.f('ix_school_subscriptions_end_date'))

    with op.batch_alter_table('school_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_events_start_date'))
        batch_op.drop_index(batch_op.f('ix_school_events_school_id'))
        batch_op.drop_index(batch_op.f('ix_school_events_end_date'))

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_school_id'))
        batch_op.drop_index(batch_op.f('ix_classrooms_homeroom_teacher_id'))

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_school_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_date'))
        batch_op.drop_index(batch_op.f('ix_attendances_classroom_id'))

    # ### end Alembic commands ###
